
sql> CREATE TABLE USUARIO(
  USERNAME VARCHAR2(30),
  NOMBRE VARCHAR2(50),
  PASSWORD VARCHAR2(20),
  ADMINISTRADOR BOOLEAN,
  AUTOR BOOLEAN,
  PRIMARY KEY (USERNAME)
)

sql> CREATE TABLE ARTICULO(
  ID INTEGER PRIMARY KEY ,
  TITULO VARCHAR2(50),
  CUERPO VARCHAR2(500),
  AUTOR VARCHAR2(30),
  DATE DATE,
  FOREIGN KEY (AUTOR)
  REFERENCES USUARIO (USERNAME)
)

sql> CREATE TABLE COMENTARIO (
  ID         INTEGER,
  COMENTARIO VARCHAR2(200),
  USUARIO    VARCHAR2(30),
  ARTICULO   INTEGER,
  FOREIGN KEY (USUARIO)
  REFERENCES USUARIO (USERNAME),
  FOREIGN KEY (ARTICULO)
    REFERENCES ARTICULO (ID),
  PRIMARY KEY (ID)
)

sql> CREATE TABLE ETIQUETA (
  ID INTEGER PRIMARY KEY ,
  ETIQUETA VARCHAR2(50),
  ARTICULO   INTEGER,
  FOREIGN KEY (ARTICULO)
    REFERENCES ARTICULO (ID)
)

INSERT INTO USUARIO (USERNAME, NOMBRE, PASSWORD, ADMINISTRADOR, AUTOR)
    VALUES ('ronyh7','Rony Hernandez','1234',true,true);